title: 'page1'

meta:
  - key1: 'value1'
    key2: 'value2'

scripts:
  - src: 'https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'
    crossorigin: anonymous
  - src: 'https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.7/semantic.min.js'
    defer:
